[package]
name = "gxcmd"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
dirs = "5.0"
walkdir = "2.5"
which = "4.4"
subprocess = "0.2"
windows = { version = "0.52", features = ["Win32_System_Environment", "Win32_Foundation"] }
