[package]
name = "gxcmd"
authors = ["Raffael <Mendgart444>"]
description = "A shell for Devs. inspired by the windows cmd, msys and git bash"
version = "0.1.0"
repository = "https://github.com/Mendgart444/gxshell"
documentation = "https://github.com/Mendgart444/gxshell/blob/main/README.md"
edition = "2021"
keywords = ["shell", "based-on-cmd", "dev-tools", "tools"]
categories = ["command-line-utilities"]
license = "MIT"

[dependencies]
#crossterm = "0.27"
dirs = "5.0"
walkdir = "2.5"
which = "4.4"
subprocess = "0.2"
sysinfo = "0.30.0"
rustyline = "12.0.0"
#windows = { version = "0.52", features = ["Win32_Security_Authorization"] }
winapi = { version = "0.3", features = ["securitybaseapi", "processthreadsapi", "winnt", "handleapi"] }
nu-ansi-term = "0.49"
reedline = "0.26"
